# Generated by Django 3.2 on 2022-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('x_rc', models.CharField(blank=True, max_length=255, null=True)),
                ('x_nif', models.CharField(blank=True, max_length=255, null=True)),
                ('x_nis', models.CharField(blank=True, max_length=255, null=True)),
                ('x_art', models.CharField(blank=True, max_length=255, null=True)),
                ('is_person', models.BooleanField(blank=True, default=False, null=True)),
                ('x_is_professional_non_commercial', models.BooleanField(blank=True, default=False, null=True)),
                ('x_professional_identity_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('x_identity_ref_delevery_date', models.CharField(blank=True, max_length=255, null=True)),
                ('x_identity_refissuing8quthority', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
